version: "3"
services:
  edu-spring-boot-rabbitmq:
    image: rabbitmq:3.11.8-management-alpine
    container_name: edu-spring-boot-rabbitmq
    hostname: edu-spring-boot-rabbitmq #used in database name
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest #default is guest
      - RABBITMQ_DEFAULT_PASS=guest #default is guest
    volumes:
      - ~/.docker-conf/rabbitmq:/var/lib/rabbitmq #database dir: /var/lib/rabbitmq/mnesia/rabbit@edu-spring-boot-rabbitmq

  edu-spring-boot-rabbitmq-producer:
    image: sbszc/edu-spring-boot-rabbitmq-producer:0.0.1-SNAPSHOT
    container_name: edu-spring-boot-rabbitmq-producer
    ports:
      - "9001:9000"
    environment:
      - RABBITMQ_HOST=edu-spring-boot-rabbitmq
      - RABBITMQ_PORT=5672
      - PORT=9000
    depends_on:
      - edu-spring-boot-rabbitmq

  edu-spring-boot-rabbitmq-consumer:
    image: sbszc/edu-spring-boot-rabbitmq-consumer:0.0.1-SNAPSHOT
    container_name: edu-spring-boot-rabbitmq-consumer
    ports:
      - "9002:9000"
    environment:
      - RABBITMQ_HOST=edu-spring-boot-rabbitmq
      - RABBITMQ_PORT=5672
      - PORT=9000
    depends_on:
      - edu-spring-boot-rabbitmq